//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.3.2
// See <a
// href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2021.08.02 at 08:51:23 PM IST
//
package com.itextos.beacon.http.generichttpapi.common.data.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="status"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="info" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="reason" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="req_id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="req_time" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
        name = "",
        propOrder =
        { "status", "reqId", "reqTime" })
@XmlRootElement(
        name = "root")
public class Root
{

    @XmlElement(
            required = true)
    protected Root.Status status;
    @XmlElement(
            name = "req_id",
            required = true)
    protected String      reqId;
    @XmlElement(
            name = "req_time",
            required = true)
    protected String      reqTime;

    /**
     * Gets the value of the status property.
     *
     * @return
     *         possible object is
     *         {@link Root.Status }
     */
    public Root.Status getStatus()
    {
        return status;
    }

    /**
     * Sets the value of the status property.
     *
     * @param value
     *              allowed object is
     *              {@link Root.Status }
     */
    public void setStatus(
            Root.Status value)
    {
        this.status = value;
    }

    /**
     * Gets the value of the reqId property.
     *
     * @return
     *         possible object is
     *         {@link String }
     */
    public String getReqId()
    {
        return reqId;
    }

    /**
     * Sets the value of the reqId property.
     *
     * @param value
     *              allowed object is
     *              {@link String }
     */
    public void setReqId(
            String value)
    {
        this.reqId = value;
    }

    /**
     * Gets the value of the reqTime property.
     *
     * @return
     *         possible object is
     *         {@link String }
     */
    public String getReqTime()
    {
        return reqTime;
    }

    /**
     * Sets the value of the reqTime property.
     *
     * @param value
     *              allowed object is
     *              {@link String }
     */
    public void setReqTime(
            String value)
    {
        this.reqTime = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within
     * this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="info" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="reason" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(
            name = "",
            propOrder =
            { "code", "info", "reason" })
    public static class Status
    {

        @XmlElement(
                required = true)
        protected String code;
        @XmlElement(
                required = true)
        protected String info;
        @XmlElement(
                required = true)
        protected String reason;

        /**
         * Gets the value of the code property.
         *
         * @return
         *         possible object is
         *         {@link String }
         */
        public String getCode()
        {
            return code;
        }

        /**
         * Sets the value of the code property.
         *
         * @param value
         *              allowed object is
         *              {@link String }
         */
        public void setCode(
                String value)
        {
            this.code = value;
        }

        /**
         * Gets the value of the info property.
         *
         * @return
         *         possible object is
         *         {@link String }
         */
        public String getInfo()
        {
            return info;
        }

        /**
         * Sets the value of the info property.
         *
         * @param value
         *              allowed object is
         *              {@link String }
         */
        public void setInfo(
                String value)
        {
            this.info = value;
        }

        /**
         * Gets the value of the reason property.
         *
         * @return
         *         possible object is
         *         {@link String }
         */
        public String getReason()
        {
            return reason;
        }

        /**
         * Sets the value of the reason property.
         *
         * @param value
         *              allowed object is
         *              {@link String }
         */
        public void setReason(
                String value)
        {
            this.reason = value;
        }

    }

}
